apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-app-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-app-proxy
  template:
    metadata:
      labels:
        app: ui-app-proxy
    spec:
      containers:
        - name: ui-app-proxy
          image: ui-app-proxy:1.0
          volumeMounts:
            - name: config-volume
              mountPath: /etc/app/
              subPath: config.yaml
      volumes:
        - name: config-volume
          configMap:
            name: app-proxy-config
            items:
              - key: config.yaml
                path: config.yaml