apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ui-app-proxy
spec:
  serviceName: ui-app-proxy
  replicas: 2
  selector:
    matchLabels:
      app: ui-app-proxy
  template:
    metadata:
      labels:
        app: ui-app-proxy
    spec:
      initContainers:
      - name: prepare-configs
        image: ubuntu
        command: ["/bin/sh"]
        args: ["-c","./app/url-update.sh"]
        volumeMounts:
          - name: config-volume
            mountPath: /app/
            subPath: config.yaml
          - name: config-volume
            mountPath: /app/
            subPath: url-update.sh
          - name: actual-config-volume
            mountPath: /etc/app
      containers:
        - name: ui-app-proxy
          image: ui-app-proxy:1.0
          volumeMounts:
            - name: actual-config-volume
              mountPath: /etc/app
      volumes:
        - name: config-volume
          configMap:
            name: app-proxy-config
            items:
              - key: config.yaml
                path: config.yaml
              - key: url-update.sh
                path: url-update.sh
        - name: actual-config-volume
          emptyDir: {}