#In the data section it contains a map name mysql_binlog_format.cnf
# and the data source which is the content of the file.

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
  labels:
    app: mysql
data:
  mysql_binlog_format.cnf: |
    [mysqld]
    binlog-format=mixed

  # kubectl exec --stdin --tty mysql-6f98c658d6-jhfk4 -- sh
  # ls /etc/mysql/conf.d
  # Kubernetes took the map name of mysql_binlog_format.cnf present it as a file
    #with the contents that were stored in the data source of the configMap.
    #The problem however is it laid that volume on top of the existing directory.
    #The default configuration files for mysql are no longer present.
    #I'd have to create all the mysql configuration files and store them into the configMap.
    #Or, I can use a subPath.
