pipeline{
    agent any 
    stages{
        stage('indentifying misconfigs using datree in helm charts'){
            steps{
                script{
                        withEnv(['DATREE_TOKEN=GJdx2cP2TCDyUY3EhQKgTc']) {
                              sh 'helm datree test datree/myapp/'
                        }

                }
            }
        }
    }

}
